SELECT DEPARTMENTS.DEPT_NAME,
	DEPARTMENT_EMPLOYEES.EMP_NO,
	EMPLOYEES.LAST_NAME,
	EMPLOYEES.FIRST_NAME
FROM DEPARTMENTS
INNER JOIN DEPARTMENT_EMPLOYEES ON DEPARTMENT_EMPLOYEES.DEPT_NO = DEPARTMENTS.DEPT_NO
INNER JOIN EMPLOYEES ON EMPLOYEES.EMP_NO = DEPARTMENT_EMPLOYEES.EMP_NO
ORDER BY DEPARTMENT_EMPLOYEES.DEPT_NO