SELECT DEPARTMENTS.DEPT_NAME,
	DEPARTMENT_MANAGERS.DEPT_NO,
	DEPARTMENT_MANAGERS.EMP_NO,
	EMPLOYEES.LAST_NAME,
	EMPLOYEES.FIRST_NAME
FROM DEPARTMENTS
INNER JOIN DEPARTMENT_MANAGERS ON DEPARTMENT_MANAGERS.DEPT_NO = DEPARTMENTS.DEPT_NO
INNER JOIN EMPLOYEES ON EMPLOYEES.EMP_NO = DEPARTMENT_MANAGERS.EMP_NO
ORDER BY DEPARTMENTS.DEPT_NAME